### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by adamkrell** [stephy/CalendarPicker#12]
Could you update the npm package to reflect the latest pull request?

**Comment by luisfuertes** [comment]
+1, i think i had installed old version component. And i see you did commit 8 days ago but code its for 2 months ago.

Can update repo?

**Comment by stephy** [comment]
Repo updated, sorry it took awhile.

**Comment by luisfuertes** [comment]
With update my project crash :(

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: UniversalWorkerNodeHandle
  Paths: /Users/myuser/Desarrollo/myproject/App/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/myuser/Desarrollo/myproject/App/node_modules/react-native-calendar-picker/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: UniversalWorkerNodeHandle
  Paths: /Users/myuser/Desarrollo/myproject/App/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/myuser/Desarrollo/myproject/App/node_modules/react-native-calendar-picker/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/myuser/Desarrollo/myproject/App/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/myuser/Desarrollo/myproject/App/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
    at run (/Users/myuser/Desarrollo/myproject/App/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/myuser/Desarrollo/myproject/App/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/myuser/Desarrollo/myproject/App/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by luisfuertes** [comment]
Ok it fix update: 
```
    "react": "^0.14.5",
    "react-native": "^0.25.1",
```

But some props doesnt run.

My code: 

  ```
<CalendarPicker
  				selectedDate={this.state.date}
  				onDateChange={this.onDateChange}
  				screenWidth={Dimensions.width}
          weekdays = {["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]}
          months = {["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]}
  				nextTitle={'Siguiente'}
  				previousTitle={'Anterior'}
          startFromMonday={true}
          selectedDayColor={'#E12518'}
  				style={{}}
  			/>
```


Before update any prop run, now "screenWidth" and "selectedDayColor " run, but "weekdays", "nextTitle", "previousTitle", "startFromMonday", "months" and "weekdays" doesnt run.

**Comment by stephy** [comment]
Yes, I see that. I really apologize. I am fixing the issue right now. I will be updating the package in the next few hours or so. I hope I didn't cause too much trouble.Best,Stephy


-------- Original Message --------
Subject: Re: [stephy/CalendarPicker] Update npm package (#12)

**Comment by luisfuertes** [comment]
No problem, thank you very much!

**Comment by luisfuertes** [comment]
Hi @stephy 
It is already updated?
Thanks!

**Comment by stephy** [comment]
yes
