### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by urska19** [stephy/CalendarPicker#70]
Just wanted to let you know, that if I install current master branch, my app will not start due to some errors. It might be nothing. Maybe just my configuration ( I am using react-native": "^0.44.0"). Latest commit that everything works fine for me is 1b460d764444620de30354c29986af4417bd6f4e 

> error: bundling: Error: ENOENT: no such file or directory, open '<path-to-app>/node_modules/react-native-calendar-picker/node_modules/react-native/Libraries/Components/ActivityIndicator/ActivityIndicator.js'
>     at Error (native)
>     at Object.fs.openSync (fs.js:640:18)
>     at Object.fs.readFileSync (fs.js:508:33)
>     at Module._readSourceCode (/Users/urska/Documents/Projects/git_repos/goopti-driver-app/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
>     at Module._getCacheProps (/Users/urska/Documents/Projects/git_repos/goopti-driver-app/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
>     at Module._readFromTransformCache (/Users/urska/Documents/Projects/git_repos/goopti-driver-app/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
>     at Module.readCached (/Users/urska/Documents/Projects/git_repos/goopti-driver-app/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
>     at Promise.resolve.then (/Users/urska/Documents/Projects/git_repos/goopti-driver-app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> 
>

**Comment by urska19** [comment]
Because this is just only some kind of observation I am closing it.
